### ISSUE TITLE
[BUG] Build script can't find win64luajit\lua51.dll

### ISSUE THREAD

**Issue by teoxoy** [whtiehack/node-luajit#5]
Build script can't find `win64luajit\lua51.dll`

> win64 need fix

That's on the readme so I guess this is related but I would like to use `node-luajit` and I can't...

Is this something easily fixable?
Tell me if I can help in any way.

OS: Win 10 Pro 64bit (1809)

**Comment by whtiehack** [comment]
Is the Visual Studio installed?

**Comment by teoxoy** [comment]
I got the windows-build-tools. Isn't that enough for node-gyp?

But that file is missing from the repo. Check the path. Shouldn't it be there?

**Comment by teoxoy** [comment]
I found this other repo (doesn't seem to be maintained anymore) but they got that dll.
https://github.com/medaeus245/node-lua/tree/master/win64luajit

**Comment by whtiehack** [comment]
What is the node version? I just tested it and it is out of date with the version above 8.0.

**Comment by teoxoy** [comment]
I got `nvm` so I tried node v8.16, v10 and v12 with no luck.

**Comment by teoxoy** [comment]
Is this a problem on my side?
Does it work for you?

**Comment by whtiehack** [comment]
This module is out of date. Sorry. 

You need to modify it yourself if you want to use it normally.

**Comment by teoxoy** [comment]
Would you accept a PR for this?

**Comment by whtiehack** [comment]
Welcome to submit PR

**Comment by teoxoy** [comment]
I ended up using [fengari](https://github.com/fengari-lua/fengari) because I need to run lua in the browser too. If the performance of fengari is not good enough on the server I will consider using `node-luajit` again.

I am unsure if the issue with the dll is on my part or with `node-luajit` - I haven't really looked into it.
Feel free to close the issue if you think it's a problem on my part.

**Comment by whtiehack** [comment]
This is the  `node-luajit` problem,not  yours.
Because support node version is too low.
I think works fine on nodejs-v6.x(linux at least).

**Comment by whtiehack** [comment]
now  `npm install https://github.com/whtiehack/node-luajit.git`   could work. 
may be you need  compile and install luajit by yourself in linux.

![image](https://user-images.githubusercontent.com/12741016/66389267-8db42500-e9fa-11e9-8eea-02c3b8a76d49.png)

**Comment by teoxoy** [comment]
A few months ago I started to use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) which allows me to have linux as my dev env.
I can get `node-luajit` to work on linux but I can't test windows anymore.

**Comment by whtiehack** [comment]
Version 2.0.3 has fixed. It has been tested with v8 and v10 on windows7 and linux.

**Comment by jfmmm** [comment]
With the latest version on windows 10 with node 10.16.3, I get this error

```powershell
MINGW64:/c/Users/username/Projects/lua-inspecter[50232]: c:\ws\src\node_contextify.cc:635: Assertion `args[1]->IsString()' failed.
 1: 00007FF6A65ADD8A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+4506
 2: 00007FF6A6588886 node::MakeCallback+4534
 3: 00007FF6A658893F node::MakeCallback+4719
 4: 00007FF6A655CD70 node::DecodeWrite+13120
 5: 00007FF6A6AB5BF2 std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+79442   
 6: 00007FF6A6AB6D59 std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+83897   
 7: 00007FF6A6AB609C std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+80636   
 8: 00007FF6A6AB5FBB std::vector<v8::internal::compiler::MoveOperands * __ptr64,v8::internal::ZoneAllocator<v8::internal::compiler::MoveOperands * __ptr64> >::_Umove+80411   
 9: 000002E6A03DC5C1
```

Work fine on 8.16.2 thought.
